num_workers: 4
batch_size: 128

dataset:
  _target_: ptls.data_load.datasets.ParquetDataset
  data_files:
    _target_: ptls.data_load.datasets.ParquetFiles
    file_path:
      - /home/jovyan/zoloev-madvillainy/LATTE/data/rosbank/ptls/train_trx.parquet
      - /home/jovyan/zoloev-madvillainy/LATTE/data/rosbank/ptls/test_trx.parquet
  i_filters:
    - _target_: ptls.data_load.iterable_processing.FeatureFilter
      keep_feature_names: cl_id
    - _target_: ptls.data_load.iterable_processing.ISeqLenLimit
      max_seq_len: 1600

output:
  path: data/${embed_file_name}
  format: pickle
