data_module: 
  _target_: ptls.data_load.data_module.cls_data_module.ClsDataModuleTrain
  type: iterable
  setup: 
    col_id: client_id
    dataset_parts: 
      data_path: ${hydra:runtime.cwd}/data/train_trx_part.parquet
      dt_dtype: int
    split_by: hash_id
    valid_size: 0.1
    valid_split_seed: 42
  train: 
    min_seq_len: 25
    buffer_size: 512
    split_strategy: 
      split_strategy: SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 200
    trx_dropout: 0.01
    num_workers: 16
    batch_size: 320
  valid: 
    split_strategy: 
      split_strategy: SampleSlices
      split_count: 5
      cnt_min: 25
      cnt_max: 100
    num_workers: 16
    batch_size: 5120
