data_module: 
  _target_: ptls.data_load.data_module.cls_data_module.ClsDataModuleTrain
  type: map
  setup: 
    dataset_files: 
      train_data_path: ${hydra:runtime.cwd}/data/train_trx_file.parquet
      test_data_path: ${hydra:runtime.cwd}/data/test_trx_file.parquet
    col_id: client_id
    col_id_dtype: int
    col_target: bins
    split_by: embeddings_validation
    fold_info: ${hydra:runtime.cwd}/conf/embeddings_validation.work/folds/folds.json
  train: 
    min_seq_len: 0
    augmentations: 
      - 
        - RandomSlice
        - 
          min_len: 150
          max_len: 700
      - 
        - DropoutTrx
        - 
          trx_dropout: 0.005
    num_workers: 16
    batch_size: 16
  valid: 
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200
    num_workers: 8
    batch_size: 16

embedding_validation_results: 
  model_name: nn
  feature_name: transf_finetuning
  output_path: ${hydra:runtime.cwd}/results/transf_finetuning_results.json

seed_everything: 42

trainer: 
  gpus: 1
  auto_select_gpus: false
  max_epochs: 6
  enable_checkpointing: false
  deterministic: true

logger_name: mles_finetuning

# pretrained_module_cls:
#   _target_: hydra.utils.get_class
#   path: ptls.lightning_modules.coles_module.CoLESModule

pretrained_encoder_path: ${hydra:runtime.cwd}/../../artifacts/scenario_age_pred/transf_model.p

pretrained_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.seq_encoder.transf_seq_encoder.TransfSeqEncoder
    train_starter: true
    shared_layers: false
    input_size: 256
    n_heads: 8
    dim_hidden: 256
    dropout: 0.1
    n_layers: 6
    use_positional_encoding: false
    max_seq_len: 1200
    use_after_mask: false
    use_src_key_padding_mask: false
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: 
        trans_date: 
          in: 800
          out: 16
        small_group: 
          in: 250
          out: 16
      numeric_values: 
        amount_rur: identity

pl_module:
  _target_: ptls.frames.supervised.SequenceToTarget
  metric_list:
    accuracy:
      _target_: torchmetrics.Accuracy
  pretrained_lr: 0.0001
  head:
    _target_: ptls.nn.Head
    input_size: 256
    use_batch_norm: true
    objective: classification
    num_classes: 4
  loss:
    _target_: torch.nn.NLLLoss
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 5e-05
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 1
    gamma: 0.6
