defaults:
  - _self_
  - dataset_unsupervised/parquet
  - inference/default
  - inference/seq_encoder/pretrained

seed_everything: 42
logger_name: barlow_twins_model
model_path: models/barlow_twins_model.p
embed_file_name: barlow_twins_embeddings

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls.frames.coles.ColesDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 2
      cnt_min: 100
      cnt_max: 500
    data: ${dataset_unsupervised.train}
  valid_data:
    _target_: ptls.frames.coles.ColesDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 2
      cnt_min: 100
      cnt_max: 500
    data: ${dataset_unsupervised.valid}
  train_batch_size: 256
  train_num_workers: 8
  valid_batch_size: 256
  valid_num_workers: 16

trainer: 
  gpus: 1
  auto_select_gpus: false
  max_epochs: 130
  enable_checkpointing: false
  deterministic: true

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 1
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder:
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: 
        event_id: 
          in: 500
          out: 16
        event_code: 
          in: 50
          out: 8
        event_type: 
          in: 6
          out: 8
        title: 
          in: 50
          out: 8
        world: 
          in: 6
          out: 8
        correct: 
          in: 4
          out: 2
      numeric_values: {}
    type: gru
    hidden_size: 100
    bidir: false
    trainable_starter: static
  head:
    _target_: ptls.nn.Head
    input_size: ${pl_module.seq_encoder.hidden_size}
    hidden_layers_sizes: [256, 256]
    use_batch_norm: true
  loss:
    _target_: ptls.frames.coles.losses.BarlowTwinsLoss
    lambd: 0.04
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.002
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 30
    gamma: 0.8
