_target_: ptls.nn.RnnSeqEncoder
trx_encoder:
  _target_: ptls.nn.TrxEncoder
  norm_embeddings: false
  embeddings_noise: 0.003
  embeddings:
    level_3:
      in: 200
      out: 16
    level_4:
      in: 800
      out: 16
    segment_id:
      in: 120
      out: 16
  numeric_values:
    trn_sum_from_iss: identity
    netto: identity
    regular_points_received: identity
type: gru
hidden_size: 800
bidir: false
trainable_starter: static
