defaults:
  - _self_
  - dataset_unsupervised/parquet
  - inference/default
  - inference/seq_encoder/pretrained

seed_everything: 42
logger_name: rtd_model
model_path: models/rtd_model.p
embed_file_name: rtd_embeddings

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls.frames.bert.RtdDataset
    min_len: 1000
    max_len: 1200
    replace_prob: 0.15
    skip_first: 1
    data: ${dataset_unsupervised.train}
  valid_data:
    _target_: ptls.frames.bert.RtdDataset
    min_len: 1000
    max_len: 1200
    replace_prob: 0.15
    skip_first: 1
    data: ${dataset_unsupervised.valid}
  train_batch_size: 128
  train_num_workers: 8
  valid_batch_size: 256
  valid_num_workers: 16

trainer:
  gpus: 1
  auto_select_gpus: false
  max_epochs: 100
  enable_checkpointing: false
  deterministic: true

pl_module:
  _target_: ptls.frames.bert.RtdModule
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder:
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.0003
      embeddings: 
        mcc: 
          in: 100
          out: 24
        channel_type: 
          in: 4
          out: 4
        currency: 
          in: 4
          out: 4
        trx_category: 
          in: 10
          out: 4
      numeric_values: 
        amount: identity
    type: lstm
    hidden_size: 512
    bidir: false
    trainable_starter: static
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    mode: max
    patience: 10
    threshold: 0.001
    min_lr: 1e-6
    verbose: true
