target: 
  file_name: /home/jovyan/sakhno/LATTE/data/rosbank/train_target.csv
  cols_id: cl_id
  col_target: target_flag
test_id_file: /home/jovyan/sakhno/LATTE/data/rosbank/test_ids.csv

model:
  _target_: lightgbm.LGBMClassifier
  n_estimators: 500
  boosting_type: gbdt
  objective: binary
  metric: auc
  subsample: 0.5
  subsample_freq: 1
  learning_rate: 0.02
  feature_fraction: 0.75
  max_depth: 7
  lambda_l1: 1
  lambda_l2: 1
  min_data_in_leaf: 50
  random_state: 42
  n_jobs: 8
  reg_alpha: null
  reg_lambda: null
  colsample_bytree: null
  min_child_samples: null
cpu_count: 4
preprocessing: 
  - _target_: sklearn.preprocessing.MaxAbsScaler
metric:
  _target_: sklearn.metrics.roc_auc_score
  _partial_: true
metric_name: roc_auc
feature_selection:
  top_k: 1024
  save_indices: true