inference_dataloader: 
  col_id: customer_id
  dataset_files: 
    - ${hydra:runtime.cwd}/data/train_trx.parquet
    - ${hydra:runtime.cwd}/data/test_trx.parquet
  SeqLenLimit: 
    max_seq_len: 1600
  loader: 
    num_workers: 4
    batch_size: 1000

data_module: 
  _target_: ptls.data_load.data_module.cls_data_module.ClsDataModuleTrain
  distribution_target_task: true
  type: map
  setup: 
    dataset_files: 
      train_data_path: ${hydra:runtime.cwd}/data/train_trx.parquet
      test_data_path: ${hydra:runtime.cwd}/data/test_trx.parquet
    col_id: customer_id
    col_id_dtype: int
    col_target: gender
    split_by: embeddings_validation
    fold_info: ${hydra:runtime.cwd}/conf/embeddings_validation.work/folds/folds.json
  train: 
    min_seq_len: 0
    augmentations: 
      - 
        - RandomSlice
        - 
          min_len: 250
          max_len: 350
          rate_for_min: 0.9
      - 
        - DropoutTrx
        - 
          trx_dropout: 0.01
    num_workers: 16
    batch_size: 32
    take_first_fraction: 0.5
  valid: 
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200
    num_workers: 8
    batch_size: 512
    take_first_fraction: 0.5
  test: 
    augmentations: []
    num_workers: 8
    batch_size: 512
    take_first_fraction: 0.5

embedding_validation_results: 
  model_name: stats
  feature_name: target_scores
  output_path: ${hydra:runtime.cwd}/results/fit_target_distribution_results_statistics.json

seed_everything: 42

trainer: 
  gpus: 0
  auto_select_gpus: false
  max_epochs: 0
  enable_checkpointing: false
  deterministic: true

logger_name: target_scores

pl_module:
  _target_: ptls.frames.supervised.SequenceToTarget
  top_negative_trx: 
    - 2010
    - 2370
    - 1010
    - 1110
    - 2330
    - 2371
    - 2011
    - 2020
    - 2331
    - 1100
    - 1030
    - 1200
    - 1210
    - 2210
    - 2021
    - 2110
    - 2340
    - 2440
    - 2460
    - 2320
    - 4010
    - 4071
    - 2341
    - 2456
    - 4051
    - 1310
    - 1410
    - 4110
    - 2100
    - 2200
    - 4011
    - 1000
    - 4210
    - 2446
    - 1510
    - 4020
    - 4500
    - 4041
    - 4090
    - 4031
    - 4021
    - 4097
    - 4100
    - 4061
    - 2000
    - 4200
    - 4096
    - 4045
    - 4035
  top_positive_trx: 
    - 7070
    - 7010
    - 7030
    - 7071
    - 7020
    - 7021
    - 7031
    - 7011
    - 6110
    - 7014
    - 7074
    - 7040
    - 7034
    - 7041
    - 6210
    - 6010
    - 7024
    - 6100
    - 7075
    - 6200
    - 7035
    - 7015
    - 7025
    - 6000
    - 8100
    - 8145
    - 7044
    - 8146
  metric_list:
    - R2n
    - R2p
    - MAPEn
    - MAPEp
    - KLn
    - KLp
    - CEn
    - CEp
  category_names: 
    - mcc_code
    - tr_type
  category_max_size: 
    mcc_code: 200
    tr_type: 100
  numeric_values: 
    amount: identity
  seq_encoder:
    _target_: ptls.seq_encoder.statistics_encoder.StatisticsEncoder
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
    distribution_target_task: true
    norm_embeddings: false
    embeddings_noise: 0.003
    embeddings: 
      tr_type: 
        in: 100
    was_logified: true
    log_scale_factor: 1
  head_layers: 
    - 
      - DummyHead
      - {}
  loss:
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.005
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 1
    gamma: 0.9
