data_module: 
  _target_: ptls.data_load.data_module.cls_data_module.ClsDataModuleTrain
  distribution_target_task: true
  type: map
  setup: 
    dataset_files: 
      train_data_path: ${hydra:runtime.cwd}/data/train_trx.parquet
      test_data_path: ${hydra:runtime.cwd}/data/test_trx.parquet
    col_id: customer_id
    col_id_dtype: int
    col_target: gender
    split_by: embeddings_validation
    fold_info: ${hydra:runtime.cwd}/conf/embeddings_validation.work/folds/folds.json
  train: 
    min_seq_len: 0
    augmentations: 
      - 
        - RandomSlice
        - 
          min_len: 250
          max_len: 350
          rate_for_min: 0.9
      - 
        - DropoutTrx
        - 
          trx_dropout: 0.01
    num_workers: 16
    batch_size: 32
    take_first_fraction: 0.5
  valid: 
    augmentations: 
      - 
        - SeqLenLimit
        - 
          max_seq_len: 1200
    num_workers: 8
    batch_size: 512
    take_first_fraction: 0.5
  test: 
    augmentations: []
    num_workers: 8
    batch_size: 512
    take_first_fraction: 0.5

embedding_validation_results: 
  model_name: agg_features
  feature_name: target_scores
  output_path: ${hydra:runtime.cwd}/results/fit_target_distribution_results_agg_features.json

seed_everything: 42

trainer: 
  gpus: 1
  auto_select_gpus: false
  max_epochs: 5
  enable_checkpointing: false
  deterministic: true

logger_name: target_scores

pl_module:
  _target_: ptls.frames.supervised.SequenceToTarget
  metric_list:
    - R2n
    - R2p
    - MAPEn
    - MAPEp
    - KLn
    - KLp
    - CEn
    - CEp
  seq_encoder:
    _target_: ptls.nn.AggFeatureSeqEncoder
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
    distribution_target_task: true
    logify_sum_mean_seqlens: true
    norm_embeddings: false
    embeddings_noise: 0.003
    embeddings: 
    numeric_values: 
      amount: identity
    was_logified: true
    log_scale_factor: 1
  head_layers: 
    - 
      - TargetHeadFromAggFeatures
      - 
        in_size: "{seq_encoder.embedding_size}"
        num_distr_classes: 6
  loss:
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.005
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 1
    gamma: 0.9
