num_workers: 4
batch_size: 1000

dataset:
  _target_: ptls.data_load.datasets.ParquetDataset
  data_files:
    _target_: ptls.data_load.datasets.ParquetFiles
    file_path:
      - data/train_trx.parquet
      - data/test_trx.parquet
  i_filters:
    - _target_: ptls.data_load.iterable_processing.FeatureFilter
      keep_feature_names: customer_id
    - _target_: ptls.data_load.iterable_processing.ISeqLenLimit
      max_seq_len: 2000

output:
  path: data/${embed_file_name}
  format: pickle
