defaults:
  - _self_
  - dataset_unsupervised/parquet

seed_everything: 42
logger_name: mles_model
model_path: models/mles_model_ft.p

data_module:
  _target_: ptls.frames.PtlsDataModule
  train_data:
    _target_: ptls.frames.coles.ColesDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 30
      cnt_max: 180
    data: ${dataset_unsupervised.train}
  valid_data:
    _target_: ptls.frames.coles.ColesDataset
    splitter:
      _target_: ptls.frames.coles.split_strategy.SampleSlices
      split_count: 5
      cnt_min: 30
      cnt_max: 180
    data: ${dataset_unsupervised.valid}
  train_batch_size: 256
  train_num_workers: 8
  valid_batch_size: 256
  valid_num_workers: 16

trainer:
  gpus: 1
  auto_select_gpus: false
  max_epochs: 10
  enable_checkpointing: false
  deterministic: true

pl_module:
  _target_: ptls.frames.coles.CoLESModule
  validation_metric:
    _target_: ptls.frames.coles.metric.BatchRecallTopK
    K: 4
    metric: cosine
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: 
        level_3: 
          in: 200
          out: 16
        level_4: 
          in: 800
          out: 16
        segment_id: 
          in: 120
          out: 16
      numeric_values: 
        trn_sum_from_iss: identity
        netto: identity
        regular_points_received: identity
    type: gru
    hidden_size: 400
    bidir: false
    trainable_starter: static
  head:
    _target_: ptls.nn.Head
    use_norm_encoder: true
  loss:
    _target_: ptls.frames.coles.losses.ContrastiveLoss
    margin: 0.5
    sampling_strategy:
      _target_: ptls.frames.coles.sampling_strategies.HardNegativePairSelector
      neg_count: 5
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.002
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 1
    gamma: 0.9025
