defaults:
  - _self_
  - data_module_supervised/default@data_module
  - pl_module/defaults

seed_everything: 42
logger_name: target_scores
fold_list:
  _target_: embeddings_validation.get_fold_list
  config_path: conf/embeddings_validation_baselines_supervised.yaml
fold_id: _

embedding_validation_results:
  model_name: nn
  feature_name: target_scores
  output_path: ${hydra:runtime.cwd}/results/fit_target_results.json

trainer:
  gpus: 1
  auto_select_gpus: false
  max_epochs: 10
  enable_checkpointing: false
  deterministic: true

pl_module:
  seq_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder: 
      _target_: ptls.nn.TrxEncoder
      norm_embeddings: false
      embeddings_noise: 0.003
      embeddings: 
        level_3: 
          in: 200
          out: 16
        level_4: 
          in: 800
          out: 16
        segment_id: 
          in: 120
          out: 16
      numeric_values: 
        trn_sum_from_iss: identity
        netto: identity
        regular_points_received: identity
    type: gru
    hidden_size: 96
    bidir: false
    trainable_starter: static
  head:
    input_size: ${pl_module.seq_encoder.hidden_size}
  optimizer_partial:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.004
    weight_decay: 0.0
  lr_scheduler_partial:
    _partial_: true
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 1
    gamma: 0.85
